/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {

//        String imgPath = "C:\\Users\\LENOVO\\Documents\\lab401\\bitmap-transformer\\app\\src\\main\\resources\\test.bmp";
//        File file=new File(imgPath);
//        System.out.println(file.exists());
//        BufferedImage buffImage = ImageIO.read(App.class.getResourceAsStream(imgPath));
//        Bitmap bg = new Bitmap();
//        bg.randomize(buffImage);




        BufferedImage image = ImageIO.read(new File("C:\\Users\\LENOVO\\Documents\\lab401\\bitmap-transformer\\app\\src\\main\\resources\\test.bmp"));
        Bitmap imageManpulation = new Bitmap() ;
        switch("randomize"){
            case "invert":
                imageManpulation.invert(image,"C:\\Users\\LENOVO\\Documents\\lab401\\bitmap-transformer\\app\\src\\main\\resources\\invert.bmp");
                break;
            case "border":
                imageManpulation.border(image,"C:\\Users\\LENOVO\\Documents\\lab401\\bitmap-transformer\\app\\src\\main\\resources\\border.bmp");
                break;
            case "randomize":
                imageManpulation.randomize(image,"C:\\Users\\LENOVO\\Documents\\lab401\\bitmap-transformer\\app\\src\\main\\resources\\randomize.bmp");
                break;
            default:
                System.out.println("Please try again" );
                break;
        }


    }

    }


